version: '3'

services:
    swapi:
        build:
            context: ./swapi
            dockerfile: Dockerfile
        container_name: swapi
        ports:
            - "8000:8000"
        volumes:
            - ./swapi:/swapi
        restart: always
        command: >
            sh -c "python3 manage.py makemigrations &&
                   python3 manage.py migrate &&
                   python3 manage.py runserver 0.0.0.0:8000"
        env_file:
            - ./.env
        depends_on:
            db:
              condition: service_healthy
             
    db:
        restart: always
        image: postgres:10-alpine
        container_name: db
        environment:
            POSTGRES_DB: swapi
            POSTGRES_USER: root
            POSTGRES_PASSWORD: systempassword
        ports:
            - "5434:5434"
        healthcheck:
            test: pg_isready -U "root" -h "db"
            interval: 10s
            timeout: 5s
            retries: 5
