# Generated by Django 4.0.3 on 2023-04-23 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CSVFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=100)),
                ('download_date', models.DateTimeField(verbose_name='download_date')),
                ('last_edited', models.DateTimeField(verbose_name='last_edited')),
            ],
        ),
    ]
