# Generated by Django 4.0.3 on 2023-04-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='csvfile',
            unique_together={('id', 'file_name', 'download_date')},
        ),
    ]
